helm:
  parameters:
  - name: image.repository
    value: 672296383659.dkr.ecr.ap-south-1.amazonaws.com/terraform-aws-ecr
    forcestring: true
  - name: image.tag
    value: c51547cf9706266570651c71dfd14ee38a1dd7a9
    forcestring: true
